projects:
  amplifyapp:
    schemaPath: amplify/backend/api/amplifyapp/build/schema.graphql
    includes:
      - data_controller
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: .
        region: ap-northeast-1
        apiId: null
        maxDepth: 2
extensions:
  amplify:
    version: 3
